//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loadify.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loadify.Localization.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to permanently add this playlist to your account?.
        /// </summary>
        public static string AddPlaylistConfirmationDialogMessage {
            get {
                return ResourceManager.GetString("AddPlaylistConfirmationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string AddPlaylistConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("AddPlaylistConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the link to the Spotify playlist you want to add..
        /// </summary>
        public static string AddPlaylistInsertLinkDialogMessage {
            get {
                return ResourceManager.GetString("AddPlaylistInsertLinkDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string AddPlaylistInsertLinkDialogTitle {
            get {
                return ResourceManager.GetString("AddPlaylistInsertLinkDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Download.
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Download.
        /// </summary>
        public static string DownloadPausedDialogCancelDownload {
            get {
                return ResourceManager.GetString("DownloadPausedDialogCancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve this issue before continuing downloading..
        /// </summary>
        public static string DownloadPausedDialogMessage {
            get {
                return ResourceManager.GetString("DownloadPausedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string DownloadPausedDialogRetry {
            get {
                return ResourceManager.GetString("DownloadPausedDialogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string DownloadPausedDialogSkip {
            get {
                return ResourceManager.GetString("DownloadPausedDialogSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Paused.
        /// </summary>
        public static string DownloadPausedDialogTitle {
            get {
                return ResourceManager.GetString("DownloadPausedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadify detected that you already have {0} of the selected tracks in your download directory. 
        ///Do you want to remove them from your download contract?.
        /// </summary>
        public static string ExistingTracksRemovalDialogMessage {
            get {
                return ResourceManager.GetString("ExistingTracksRemovalDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected existing Tracks.
        /// </summary>
        public static string ExistingTracksRemovalDialogTitle {
            get {
                return ResourceManager.GetString("ExistingTracksRemovalDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to permanently remove this playlist from your account?.
        /// </summary>
        public static string RemovePlaylistConfirmationDialogMessage {
            get {
                return ResourceManager.GetString("RemovePlaylistConfirmationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Playlist.
        /// </summary>
        public static string RemovePlaylistConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("RemovePlaylistConfirmationDialogTitle", resourceCulture);
            }
        }
    }
}
