//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loadify.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loadify.Localization.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Directory.
        /// </summary>
        public static string CacheDirectory {
            get {
                return ResourceManager.GetString("CacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where the cache and other temporary files will be stored.
        /// </summary>
        public static string CacheDirectoryInfo {
            get {
                return ResourceManager.GetString("CacheDirectoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove uncompressed audio files after they were converted.
        /// </summary>
        public static string CleanupAfterConversion {
            get {
                return ResourceManager.GetString("CleanupAfterConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Directory.
        /// </summary>
        public static string DownloadDirectory {
            get {
                return ResourceManager.GetString("DownloadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where the downloaded files will be stored.
        /// </summary>
        public static string DownloadDirectoryInfo {
            get {
                return ResourceManager.GetString("DownloadDirectoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management.
        /// </summary>
        public static string FileManagement {
            get {
                return ResourceManager.GetString("FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Track Detection.
        /// </summary>
        public static string LocalTrackDetection {
            get {
                return ResourceManager.GetString("LocalTrackDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me for removing tracks that were detected to be already downloaded.
        /// </summary>
        public static string NotifyLocalTrackDetections {
            get {
                return ResourceManager.GetString("NotifyLocalTrackDetections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip tracks that can not be downloaded automatically.
        /// </summary>
        public static string SkipOnDownloadFailures {
            get {
                return ResourceManager.GetString("SkipOnDownloadFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Language.
        /// </summary>
        public static string UILanguage {
            get {
                return ResourceManager.GetString("UILanguage", resourceCulture);
            }
        }
    }
}
